### ISSUE TITLE
brk(), sbrk(): Possible logic change required

### ISSUE THREAD

**Issue by DoctorWkt** [eschaton/MINIXCompat#11]
Chris, in your `MINIXCompat_SysCall_brk()` code, you have the comment:

```
// keep track of the current break since we never allow  it to be set lower.
```
I think this logic should be changed to be:
```
// Keep track of the initial break since we never allow the current break to be lower than this.
```

I think the current logic is causing the shell to spit out, e.g. `echo: program too big` error messages. After the shell forks, it's quite safe for it to lower the current break unless it drops below the initial break value (which would have been set to just after the BSS).

I've used my suggested logic [here](https://github.com/DoctorWkt/Fuzemsys/blob/eb273248b55d5e491c9166bd6b528baf2122fce6/emulators/syscalls.c#L950) and it works fine.

**Comment by DoctorWkt** [comment]
Also, have a look at this function in `sort.c`:

```
/* Sort () sorts the input in memory starting at mem_top. */
sort()
{
  ...

/* Set up the line table */
/* WKT: line_table gets set to the break value before the sbrk(). msbrk() is a
   wrapper around sbrk() */
  line_table = (char **) msbrk(count * sizeof(char *) + sizeof(char *));

  ...

/* Free line table */
/* WKT: This calls brk() and lowers the break value back to what it was before the above code
   raised it. */
  mbrk(line_table);
}
```

**Comment by eschaton** [comment]
Yeah, I figure this is probably a place where substantial bugs lie, both in the code that calls `brk(2)` and also in my implementation. I even tried to get away with returning a fixed value at first!

**Comment by eschaton** [comment]
I suspect this may also be why `cc` isn't working.
