### ISSUE TITLE
EBADEXEC?

### ISSUE THREAD

**Issue by DoctorWkt** [eschaton/MINIXCompat#3]
Hi Chris, I'm trying to compile this on Linux (Devuan Daedalus) with clang 14.0.6. I'm getting a missing errno:

```
MINIXCompat/MINIXCompat_Executable.c:241:25: error: use of undeclared identifier 'EBADEXEC'
                return -EBADEXEC;
```
Can I replace the error number with something else? I'm guessing this is Apple specific. Thanks!

**Comment by eschaton** [comment]
This will be addressed by #2, as will a couple of other needed tweaks.
