### ISSUE TITLE
Finish signal handling implementation

### ISSUE THREAD

**Issue by eschaton** [eschaton/MINIXCompat#6]
Most of the infrastructure that would be needed by `signal(2)` is in place (and `kill(2)` is implemented) but when a MINIXCompat process is signaled the handlers aren't actually called yet.

This is likely to be important for running `cc` since signals are one of the only ways (other than file locking) to handle multi-process coordination on MINIX 1.5.

**Comment by eschaton** [comment]
Here's my first idea for how to deliver a signal to the 68K side:

We have the 68K-side address of the handler for the signal, so we just need to push the signal number itself on a  stack, jump to that, and switch back to host code when it's done. That means we need to provide two things: A stack on which to execute the handler, and a means of transitioning immediately back to host code when done.

We can provide a stack by just reserving another portion of the address space for it, such as the region immediately below the user stack, and setting that to the emulated `SP` (and "pushing" the signal number to it) before jumping to the handler. That's quite straightforward.

Transitioning back to the host as soon as the handler is complete is a little more complicated. My first inclination is to have the `TRAP #1` instruction do that, and to synthesize a `JSR` to the signal handler address instead of setting the emulated `PC` to its address directly. That way we can synthesize a `TRAP #1` after that `JSR` that transitions back to the host and says the emulated handler is done and that we can go back to normal emulation (or run another signal handler, if needed).

**Comment by DoctorWkt** [comment]
What about this as an idea. When there is a signal to deliver and there is a registered handler, i.e. just before you call `return m68k_execute(cycles);`, perhaps you can do this:

 * push the current PC (REG_PC) on the stack (2 bytes)
 * push `rts` then `addq.l #6,sp` on the stack (4 bytes) and record the `addq.l` location
 * push the mapped signal number on the stack (2 bytes)
 * push the address of the `addq.l` instruction on the stack (2 bytes)
 * set REG_PC to the address of the MINIX signal handler

Then, when you call `m68k_execute()`, it will run the signal handler. At the end, when it does the `rts`, it will jump to the `addq.l` instruction. This will remove the signal number, the `rts` and the `addq.l` from the stack, do the `rts` and then jump to the PC which the code would have done if there was no signal handler.

**Comment by eschaton** [comment]
Good idea! That sounds a lot more tractable and doesn't require a bunch of bookkeeping, and it's not really a big deal either to require an executable stack.

**Comment by eschaton** [comment]
Oh yeah, and the addresses are actually going to be 4 bytes, not 2. :) But I get your meaning!

**Comment by eschaton** [comment]
MINIX signal handling always specifies `_begsig` from `catchsig.s` as the handler when calling `signal(2)` when then goes to the vector table to actually call the user-side handler.

The trick is that `_begsig` uses `RTR` to return rather than `RTS` so we also need to push the original value of the CCR restore after the PC to resume at.

**Comment by eschaton** [comment]
What this means is that all we actually need to do is push (in this order) the PC, the SR, and the signal number, and then set the PC to the signal handler (which is always `_begsig`). It will take caare of the stack for us.
